{ config, inputs, pkgs, user, lib, ... }:

let
  keyFiles = [
    "${inputs.home-estate}/authorized_keys"
  ];
in
{
  users.users = {
    ${user} = {
      isNormalUser = true;
      extraGroups = [ "networkmanager" "wheel" "docker" "libvirtd" ];
      home = "/home/${user}";
      shell = lib.mkDefault pkgs.fish;
      # /etc/ssh/authorized_keys.d/${user}
      openssh.authorizedKeys.keyFiles = keyFiles;
      packages = with pkgs; lib.mkDefault [ fish ];
      # we have to use initialHashedPassword here when using tmpfs for /
      # generated by `mkpasswd -m scrypt`
      initialHashedPassword = "$7$CU..../....nnOYNef.N4rHN9q8TseVo1$cgf5w2iAkrNXxU1uwGI0HlFFGuwcU3l507b67v0Kp49";
    };

    root = {
      shell = pkgs.bash;
      inherit (config.users.users."${user}") initialHashedPassword;
    };
  };
}
