{ config, inputs, user, ... }:

{
  imports = [ ./default.nix ];

  users.users = {
    # we have to use initialHashedPassword here when using tmpfs for /
    # generated by `mkpasswd -m scrypt`
    # users.${user}.initialHashedPassword = "";
    ${user}.hashedPasswordFile = config.sops.secrets."login/initialHashedPassword".path;

    root = {
      inherit (config.users.users."${user}") initialHashedPassword;
      openssh.authorizedKeys.keyFiles = [ "${inputs.home-estate}/authorized_keys" ];
    };
  };
}
