{ config, inputs, user, ... }:

{
  imports = [ ./default.nix ];

  users.users = {
    # we have to use initialHashedPassword here when using tmpfs for /
    # generated by `mkpasswd -m scrypt`
    ${user}.initialHashedPassword = "$7$CU..../....nnOYNef.N4rHN9q8TseVo1$cgf5w2iAkrNXxU1uwGI0HlFFGuwcU3l507b67v0Kp49";

    root = {
      inherit (config.users.users."${user}") initialHashedPassword;
      openssh.authorizedKeys.keyFiles = [ "${inputs.home-estate}/authorized_keys" ];
    };
  };
}
