{ config, inputs, user, ... }:

{
  imports = [ ./default.nix ];

  users = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    users.${user}.initialHashedPassword = builtins.readFile config.sops.secrets."login/initialHashedPassword".path;

    users.root = {
      initialHashedPassword = config.users.users."${user}".initialHashedPassword;
      openssh.authorizedKeys.keyFiles = [ "${inputs.home-estate}/authorized_keys" ];
    };
  };
}
