---
name: (Cron) Synchronize upstream flake inputs
on:
  workflow_dispatch:
  schedule:
    # Run this Action every 7 days at 0:00pm UTC
    - cron: "0 0 */7 * *"

env:
  targets: |
    nixpkgs
    pilots
    chaotic
    home-manager
    sops-nix
    nixpkgs-wayland
    hyprland
    neovim-nightly-overlay
    impermanence
    pre-commit-hooks
    microvm
    nix-fast-build
    auto-cpufreq

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Auth Token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@main
        with:
          ref: master
          # submodules: true
          token: "${{ secrets.ACCESS_TOKEN }}"

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Update flake.lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "chore(flake) update flake.lock for the selected upstream inputs"
          pr-labels: |
            flake-lock
            automated
          inputs: ${{ env.targets }}
          token: ${{ steps.generate_token.outputs.token }}

      - name: Print PR number
        run: |
          echo "Pull request number is ${{ steps.update-flake-lock.outputs.pull-request-number }}"
