name: (Cron) Poll changes from upstream repo (chaotic/nyx)

on:
  workflow_dispatch:
  schedule:
    # Run this Action every day at 1:00am UTC
    - cron: '0 1 * * *'
  push:
    branches:
      - poll-changes-from-nyx

jobs:
  poll-upstream-changes:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    strategy:
      matrix:
        include:
          - repo: chaotic/nyx
            ref: main
            label: upstream-nyx-changes
            path: pkgs/linux-cachyos/versions-hardened.json
      fail-fast: false
    steps:
      - name: Generate GitHub Auth Token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.ref }}
          fetch-depth: 0
          #   submodules: true

          # - name: Poll changes from GitHub repo (${{ env.REPO_TO_SYNC }}
          #   uses: poll-github-repo/action@v1
          #   with:
          #     token: ${{ steps.generate_token.outputs.token }}
          #     yes-create-issues: true
          #     cache-path: .github/artifacts/${{ matrix.path }}.last-sync
          #     repo-to-sync: ${{ matrix.repo }}
          #     path-to-sync: ${{ matrix.path }}
          #     tracking-issue-label: ${{ matrix.label }}
          #     tracking-issue-title: "[Sync] Updates on ${{ matrix.repo }} {{ path }}: {{ sha-short }}"
          #     tracking-issue-body: |
          #       ## Summary

          #       New commit in ${{ matrix.repo }} ({{ commit-date }}) ({{ sha-full }}):

          #       {{ message }} [link]({{ url }})

      - name: Poll changes from GitHub repo (${{ env.REPO_TO_SYNC }}
        id: poll-changes
        uses: tj-actions/changed-files@main
        with:
          files: ${{ matrix.path }}

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.poll-changes.outputs.all_changed_files }}
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: $ALL_CHANGED_FILES"
